#
# From kubernetes-device-plugins/manifests/kvm-ds.yml
#
# License: MIT
#
# Deploys Daemon Set with kvm device plugin, which allows Pods access to /dev/kvm using "resource allocation" mechanism
#
# Download the plugin binary from  quay.io
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: device-plugin-kvm
  name: device-plugin-kvm
spec:
  selector:
    matchLabels:
      name: device-plugin-kvm
  template:
    metadata:
      labels:
        name: device-plugin-kvm
    spec:
      containers:
      - name: device-plugin-kvm
        image: quay.io/kubevirt/device-plugin-kvm
        args: ["-v", "3", "-logtostderr"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
