apiVersion: apps/v1
kind: Deployment
metadata:
  name: pykm-deployment
  labels:
    app: pykm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pykm
  template:
    metadata:
      labels:
        app: pykm
    spec:
      containers:
      - name: pykm
        image: kontainkubecr.azurecr.io/python-km:msterin-kube
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
           requests:
              devices.kubevirt.io/kvm: "1"
           limits:
              devices.kubevirt.io/kvm: "1"
        args: [ "/cpython/python.km", "-u", "/scripts/hello_loop.py"]
