# Copyright 2021 Kontain
# Derived from: 
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kontain-kkm-installer
  namespace: kube-system
  labels:
    app: kkm-installer
spec:
  selector:
    matchLabels:
      app: kkm-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kontain-kkm-installer
        app: kkm-installer
    spec:
      containers:
      - image: centos:7    # ubuntu:18.04
        name: kkm-installer
        command: ["/scripts/entrypoint.sh"]
        env:
        - name: KONTAIN_RELEASE_URL
          value: https://github.com/kontainapp/km/releases/download/v0.1-edge/kontain_bin.tar.gz
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-entrypoint
          mountPath: /scripts-lib
        - name: entrypoint
          mountPath: /scripts
      volumes:
      - name: entrypoint
        configMap:
          name: kkm-install-entrypoint
          defaultMode: 0744
      - name: lib-entrypoint
        configMap:
          name: kontain-install-lib
          defaultMode: 0744
